#line 2 "expr-tokens.c"

#line 4 "expr-tokens.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE nx_expr_parser_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via nx_expr_parser_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void nx_expr_parser_restart (FILE *input_file ,yyscan_t yyscanner );
void nx_expr_parser__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE nx_expr_parser__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void nx_expr_parser__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void nx_expr_parser__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void nx_expr_parser_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void nx_expr_parser_pop_buffer_state (yyscan_t yyscanner );

static void nx_expr_parser_ensure_buffer_stack (yyscan_t yyscanner );
static void nx_expr_parser__load_buffer_state (yyscan_t yyscanner );
static void nx_expr_parser__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER nx_expr_parser__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE nx_expr_parser__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE nx_expr_parser__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE nx_expr_parser__scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *nx_expr_parser_alloc (yy_size_t ,yyscan_t yyscanner );
void *nx_expr_parser_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void nx_expr_parser_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer nx_expr_parser__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        nx_expr_parser_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nx_expr_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        nx_expr_parser_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nx_expr_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define nx_expr_parser_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[187] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   73,   70,
       67,   69,   70,    1,   68,   70,   48,   41,    2,   57,
       58,   46,   49,   62,   50,   47,    6,    6,   61,   56,
       35,   54,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   43,   59,   42,   60,   32,   32,   34,
       32,   11,   11,   12,   17,   17,   19,   71,   21,   21,
       23,   71,   25,   25,   27,   71,   29,   29,   28,   71,
       31,   31,   30,   13,   72,   15,   71,   67,   52,   10,
       68,   66,   66,   63,    6,    6,    0,    6,    6,    0,

        6,   55,   51,    9,   53,    0,   65,   65,   65,   65,
       65,   44,   65,   39,   65,   65,   65,   32,   33,   11,
       17,   18,   16,   21,   22,   20,   25,   26,   24,   13,
       14,   66,   63,    0,    6,    6,    6,    0,   38,   65,
       65,   65,   36,   65,   65,   40,    0,    0,    6,    6,
       64,   65,   45,   65,    3,   65,    0,    0,    0,   64,
       65,    4,    8,    0,    0,    0,   65,    5,    0,    0,
       37,    5,    0,    5,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   28,   28,   29,   30,   31,
       32,   28,   33,   28,   34,   35,   36,   37,   38,   28,
       28,   39,   40,   41,   42,   28,   28,   43,   28,   28,
        1,   44,    1,   45,   46,    1,   47,   28,   28,   48,

       49,   50,   32,   28,   51,   28,   34,   52,   36,   53,
       54,   28,   28,   55,   56,   57,   58,   28,   28,   59,
       28,   28,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    5,    6,    7,    8,
        8,    1,    1,    1,    1,    1,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    7,    1,   10,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[210] =
    {   0,
        0,    0,   61,   62,   63,   66,   67,   68,   69,   70,
       72,   73,   87,   97,   95,  119,   78,  105,  555,  556,
       81,  556,   76,  556,    0,   58,  556,  556,  556,  556,
      556,  556,  556,  556,   73,  556,  142,  147,  556,  526,
       78,  517,  119,  510,  141,  152,  130,  149,  156,  167,
      169,  165,  171,  556,  556,  556,  556,    0,    0,  556,
      501,    0,    0,  556,    0,    0,  556,  468,    0,    0,
      556,  455,    0,    0,  556,  444,  556,  556,  556,  556,
      556,  556,  556,  100,  556,  556,  438,  187,  556,  556,
        0,  556,   75,    0,  194,  199,  105,  218,  556,    0,

      223,  556,  556,  556,  556,  417,  343,  194,  190,  176,
      210,  324,  217,  305,  229,  200,  230,    0,  556,    0,
        0,  301,  556,    0,  296,  556,    0,  277,  556,  193,
      556,  129,    0,  243,  247,  164,  252,    0,  258,  243,
      260,  249,  239,  261,  263,  234,  192,  277,  267,  287,
        0,  265,  232,  283,  188,  275,  296,  185,  306,    0,
      294,  175,  137,  308,  313,  315,  313,  317,  126,  104,
       98,  319,  324,  556,  326,  106,  328,  330,   77,  332,
      334,   62,  336,  338,  556,  556,  361,  371,  381,  391,
      401,  411,  421,  431,  441,  444,  450,  460,  470,  480,

      490,  500,  510,  520,  530,  535,  538,  539,  544
    } ;

static yyconst flex_int16_t yy_def[210] =
    {   0,
      186,    1,  187,  187,  188,  188,  189,  189,  190,  190,
      191,  191,  192,  192,  193,  193,  194,  194,  186,  186,
      186,  186,  186,  186,  195,  196,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  186,  186,  186,  186,  198,  198,  186,
      198,  199,  199,  186,  200,  200,  186,  201,  202,  202,
      186,  203,  204,  204,  186,  205,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      195,  186,  186,  206,  186,  186,  186,  186,  186,  207,

      186,  186,  186,  186,  186,  186,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  198,  186,  199,
      200,  201,  186,  202,  203,  186,  204,  205,  186,  186,
      186,  186,  206,  186,  186,  207,  186,  208,  197,  197,
      197,  197,  197,  197,  197,  197,  186,  186,  207,  186,
      209,  197,  197,  197,  197,  197,  186,  186,  186,  209,
      197,  197,  197,  186,  186,  186,  197,  186,  186,  186,
      197,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,    0,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,

      186,  186,  186,  186,  186,  186,  186,  186,  186
    } ;

static yyconst flex_int16_t yy_nxt[620] =
    {   0,
       20,   21,   22,   21,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   20,   36,   37,
       38,   20,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   44,   48,   44,   44,   44,   49,   50,   44,   44,
       51,   52,   53,   20,   54,   44,   43,   45,   46,   47,
       48,   44,   49,   50,   44,   44,   51,   52,   53,   55,
       56,   57,   20,   59,   59,   63,   60,   60,   63,   66,
       66,   70,   70,   64,   74,   74,   64,   92,   93,   84,
       85,   84,   88,  183,   88,   67,   67,   71,   71,   78,
       75,   75,   95,   96,  132,  132,   86,   82,  180,   78,

       89,  130,  103,  130,   61,   61,   84,   85,   84,  177,
       68,   68,   72,   72,  106,   76,   76,   87,   79,   79,
      173,   82,   79,   86,  134,  134,   79,   83,   79,   79,
       83,   80,   79,   87,   83,  106,   79,   79,   90,   80,
      104,   80,   79,  164,   87,   83,  106,   79,  132,  132,
       83,   83,   79,  106,   83,  108,  111,  106,   83,   97,
       87,   98,   98,   80,   97,  106,  101,  101,  106,   83,
      109,  108,  106,   99,   83,   99,  111,   99,   99,  112,
       99,  106,   99,  106,  100,  106,  110,  106,   88,  109,
       88,  106,  106,  113,  130,  149,  130,  149,  112,  149,

      100,  116,  147,  110,  106,  114,  106,  115,  117,  113,
      106,  157,  157,   96,   96,  141,  106,  116,   96,   96,
      140,  114,  139,  115,  117,   99,  106,   99,  145,   99,
       99,  141,   99,  106,   99,   97,  100,  135,  135,  140,
       97,  139,  137,  137,  142,  106,  106,  145,  106,   99,
      106,   99,  100,   99,   99,  106,   99,  143,   99,  106,
      147,  142,  148,  148,   97,  106,   96,   96,  146,   97,
      144,  150,  150,  143,  106,  152,  106,  106,   99,  106,
       99,  106,   99,   99,  146,   99,  144,   99,  154,  153,
      155,  106,  156,  152,  147,  186,  158,  158,  149,  106,

      149,  161,  149,  159,  154,  163,   96,   96,  153,  155,
      106,  156,  162,  164,  186,  165,  165,  161,   99,  186,
       99,  106,   99,  167,  163,  166,  166,  168,  168,  106,
      164,  162,  169,  169,  170,  170,  172,  172,  174,  174,
      106,  171,  167,  175,  175,  176,  176,  178,  178,  179,
      179,  181,  181,  182,  182,  184,  184,  185,  185,  106,
      171,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   91,  138,   91,   91,   91,   91,   91,   91,   91,
       91,   94,   94,   94,  107,  107,  131,  107,  107,  107,
      118,  118,  129,  118,  118,  118,  118,  118,  118,  118,
      120,  120,  120,  126,  120,  120,  120,  120,  120,  120,
      121,  121,  121,  121,  121,  121,  123,  121,  121,  121,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,

      124,  124,  124,  124,  124,  124,  119,  124,  124,  124,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      127,  127,  127,  127,  127,  127,  106,  127,  127,  127,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      133,  105,  133,  133,  133,  136,  136,  151,  151,  160,
      102,  160,  160,  160,  186,   19,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,

      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186
    } ;

static yyconst flex_int16_t yy_chk[620] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    3,    4,    6,    7,
        8,    9,   10,    5,   11,   12,    6,   26,   26,   17,
       17,   17,   21,  182,   21,    7,    8,    9,   10,   13,
       11,   12,   35,   35,   93,   93,   17,   15,  179,   14,

       23,   84,   41,   84,    3,    4,   18,   18,   18,  176,
        7,    8,    9,   10,  171,   11,   12,   17,   13,   13,
      170,   16,   13,   18,   97,   97,   13,   15,   14,   14,
       15,   13,   14,   17,   15,   43,   14,   13,   23,   15,
       41,   14,   13,  169,   18,   15,   47,   14,  132,  132,
       15,   16,   14,  163,   16,   43,   47,   45,   16,   37,
       18,   37,   37,   16,   38,   48,   38,   38,   46,   16,
       45,   43,   49,   37,   16,   37,   47,   37,   38,   48,
       38,   52,   38,   50,   37,   51,   46,   53,   88,   45,
       88,  162,  110,   49,  130,  136,  130,  136,   48,  136,

       37,   52,  158,   46,  155,   50,  109,   51,   53,   49,
      108,  147,  147,   95,   95,  110,  116,   52,   96,   96,
      109,   50,  108,   51,   53,   95,  111,   95,  116,   95,
       96,  110,   96,  113,   96,   98,   95,   98,   98,  109,
      101,  108,  101,  101,  111,  115,  117,  116,  153,   98,
      146,   98,   95,   98,  101,  143,  101,  113,  101,  140,
      134,  111,  134,  134,  135,  142,  135,  135,  117,  137,
      115,  137,  137,  113,  139,  140,  141,  144,  135,  145,
      135,  152,  135,  137,  117,  137,  115,  137,  142,  141,
      144,  156,  145,  140,  148,  128,  148,  148,  149,  154,

      149,  152,  149,  150,  142,  156,  150,  150,  141,  144,
      161,  145,  154,  157,  125,  157,  157,  152,  150,  122,
      150,  114,  150,  161,  156,  159,  159,  164,  164,  167,
      165,  154,  165,  165,  166,  166,  168,  168,  172,  172,
      112,  167,  161,  173,  173,  175,  175,  177,  177,  178,
      178,  180,  180,  181,  181,  183,  183,  184,  184,  107,
      167,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  190,  190,  190,  190,  190,  190,  190,  190,  190,

      190,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  194,  194,  194,  194,  194,  194,  194,  194,  194,
      194,  195,  106,  195,  195,  195,  195,  195,  195,  195,
      195,  196,  196,  196,  197,  197,   87,  197,  197,  197,
      198,  198,   76,  198,  198,  198,  198,  198,  198,  198,
      199,  199,  199,   72,  199,  199,  199,  199,  199,  199,
      200,  200,  200,  200,  200,  200,   68,  200,  200,  200,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,

      202,  202,  202,  202,  202,  202,   61,  202,  202,  202,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      204,  204,  204,  204,  204,  204,   44,  204,  204,  204,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      206,   42,  206,  206,  206,  207,  207,  208,  208,  209,
       40,  209,  209,  209,   19,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,

      186,  186,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  186,  186
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "expr-tokens.l"
/*
 * This file is part of the nxlog log collector tool.
 * See the file LICENSE in the source root for licensing terms.
 * Website: http://nxlog.org
 * Author: Botond Botyanszki <botond.botyanszki@nxlog.org>
 */
#line 12 "expr-tokens.l"
#include "expr.h"
#include "str.h"
#include "expr-grammar.h"
#include "expr-parser.h"
#include "error_debug.h"

#define NX_LOGMODULE NX_LOGMODULE_MODULE

#define PARSER nx_expr_parser_get_extra(yyscanner)
#define YY_INPUT(buffer, res, max_size)             	    \
    do {                                                    \
        if (PARSER->pos >= PARSER->length)                  \
            res = YY_NULL;                                  \
        else                                                \
        {                                                   \
            res = PARSER->length - PARSER->pos;             \
            res > (int)max_size ? res = max_size : 0;       \
            memcpy(buffer, PARSER->buf + PARSER->pos, res); \
            PARSER->pos += res;                             \
        }                                                   \
    } while (0)

#define YY_USER_ACTION PARSER->linepos += yyleng;









#line 683 "expr-tokens.c"

#define INITIAL 0
#define DOUBLEQUOTE 1
#define SINGLEQUOTE 2
#define REGEXPQUOTE 3
#define REGEXPREPLACEQUOTE 4
#define REGEXPREPLACEQUOTE2 5
#define REGEXPREPLACEMODIFIERS 6
#define REGEXPMODIFIERS 7
#define REGEXP 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int nx_expr_parser_lex_init (yyscan_t* scanner);

int nx_expr_parser_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int nx_expr_parser_lex_destroy (yyscan_t yyscanner );

int nx_expr_parser_get_debug (yyscan_t yyscanner );

void nx_expr_parser_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE nx_expr_parser_get_extra (yyscan_t yyscanner );

void nx_expr_parser_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *nx_expr_parser_get_in (yyscan_t yyscanner );

void nx_expr_parser_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *nx_expr_parser_get_out (yyscan_t yyscanner );

void nx_expr_parser_set_out  (FILE * out_str ,yyscan_t yyscanner );

int nx_expr_parser_get_leng (yyscan_t yyscanner );

char *nx_expr_parser_get_text (yyscan_t yyscanner );

int nx_expr_parser_get_lineno (yyscan_t yyscanner );

void nx_expr_parser_set_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * nx_expr_parser_get_lval (yyscan_t yyscanner );

void nx_expr_parser_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int nx_expr_parser_wrap (yyscan_t yyscanner );
#else
extern int nx_expr_parser_wrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int nx_expr_parser_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int nx_expr_parser_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 60 "expr-tokens.l"


#line 932 "expr-tokens.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			nx_expr_parser_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				nx_expr_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		nx_expr_parser__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 187 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 556 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "expr-tokens.l"
{ yylval->string = NULL; BEGIN(DOUBLEQUOTE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 63 "expr-tokens.l"
{ yylval->string = NULL; BEGIN(SINGLEQUOTE);  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "expr-tokens.l"
{ yylval->bool = TRUE; return ( TOKEN_BOOLEAN ); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "expr-tokens.l"
{ yylval->bool = FALSE; return ( TOKEN_BOOLEAN ); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "expr-tokens.l"
{ yylval->string = yytext; return ( TOKEN_IP4ADDR ); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 67 "expr-tokens.l"
{ yylval->string = yytext; return ( TOKEN_INTEGER ); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "expr-tokens.l"
{ yylval->string = yytext; return ( TOKEN_DATETIME ); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "expr-tokens.l"
{ yylval->string = "UNDEF"; return ( TOKEN_UNDEF ); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "expr-tokens.l"
{ BEGIN(REGEXP); return ( TOKEN_REGMATCH ); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "expr-tokens.l"
{ BEGIN(REGEXP); return ( TOKEN_NOTREGMATCH ); }
	YY_BREAK

case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 76 "expr-tokens.l"
{ nx_expr_parser_append_string(&(yylval->string), yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 77 "expr-tokens.l"
{
			  BEGIN(INITIAL);
			  return ( TOKEN_STRING );
                        }
	YY_BREAK


case 13:
YY_RULE_SETUP
#line 84 "expr-tokens.l"
{  }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 85 "expr-tokens.l"
{ log_debug("regexpreplacequote start"); yylval->regexp[0] = NULL; yylval->regexp[1] = NULL; yylval->regexp[2] = NULL; BEGIN(REGEXPREPLACEQUOTE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 86 "expr-tokens.l"
{ log_debug("regexpquote start"); yylval->regexp[0] = NULL; yylval->regexp[1] = NULL; yylval->regexp[2] = NULL; BEGIN(REGEXPQUOTE); }
	YY_BREAK


case 16:
YY_RULE_SETUP
#line 90 "expr-tokens.l"
{ log_debug("regexp: append backslash"); nx_expr_parser_append_string(&(yylval->string), "/"); }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 91 "expr-tokens.l"
{ log_debug("regexp: append [%s]", yytext); nx_expr_parser_append_string(&(yylval->string), yytext); }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 92 "expr-tokens.l"
{ log_debug("regexp: append [%s]", yytext); nx_expr_parser_append_string(&(yylval->string), yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "expr-tokens.l"
{
			  log_debug("regexpquote end");
			  BEGIN(REGEXPMODIFIERS);
                        }
	YY_BREAK


case 20:
YY_RULE_SETUP
#line 100 "expr-tokens.l"
{ log_debug("regexpreplacequote: append backslash"); nx_expr_parser_append_string(&(yylval->regexp[0]), "/"); }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 101 "expr-tokens.l"
{ log_debug("regexpreplacequote: append [%s]", yytext); nx_expr_parser_append_string(&(yylval->regexp[0]), yytext); }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 102 "expr-tokens.l"
{ log_debug("regexpreplacequote: append [%s]", yytext); nx_expr_parser_append_string(&(yylval->regexp[0]), yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "expr-tokens.l"
{
			  log_debug("regexpreplacequote2 begin"); 
			  BEGIN(REGEXPREPLACEQUOTE2);
                        }
	YY_BREAK


case 24:
YY_RULE_SETUP
#line 110 "expr-tokens.l"
{ log_debug("regexpreplacequote2: append backslash"); nx_expr_parser_append_string(&(yylval->regexp[1]), "/"); }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 111 "expr-tokens.l"
{ log_debug("regexpreplacequote2: append [%s]", yytext); nx_expr_parser_append_string(&(yylval->regexp[1]), yytext); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 112 "expr-tokens.l"
{ log_debug("regexpreplacequote2: append [%s]", yytext); nx_expr_parser_append_string(&(yylval->regexp[1]), yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 113 "expr-tokens.l"
{
			  log_debug("regexpreplacequote2 end"); 
			  if ( yylval->regexp[1] == NULL ) yylval->regexp[1] = strdup("");
			  BEGIN(REGEXPREPLACEMODIFIERS);
                        }
	YY_BREAK


case 28:
YY_RULE_SETUP
#line 121 "expr-tokens.l"
{
			  log_debug("regexpreplacemodifiers begin [%s]", yytext); 
			  nx_expr_parser_append_string(&(yylval->regexp[2]), yytext);
                        }
	YY_BREAK
case YY_STATE_EOF(REGEXPREPLACEMODIFIERS):
#line 125 "expr-tokens.l"
{
			  log_debug("regexpreplacemodifiers end with eof"); 
			  BEGIN(INITIAL);
			  return ( TOKEN_REGEXPREPLACE );
                        }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 130 "expr-tokens.l"
{
			  log_debug("regexpreplacemodifiers end");
			  unput(yytext[0]);
			  BEGIN(INITIAL);
			  return ( TOKEN_REGEXPREPLACE );
                        }
	YY_BREAK


case 30:
YY_RULE_SETUP
#line 139 "expr-tokens.l"
{
			  log_debug("regexpmodifiers begin [%s]", yytext); 
			  nx_expr_parser_append_string(&(yylval->regexp[2]), yytext);
                        }
	YY_BREAK
case YY_STATE_EOF(REGEXPMODIFIERS):
#line 143 "expr-tokens.l"
{
			  log_debug("regexpmodifiers end with eof"); 
			  BEGIN(INITIAL);
			  return ( TOKEN_REGEXP );
                        }
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 148 "expr-tokens.l"
{
			  log_debug("regexpmodifiers end"); 
			  unput(yytext[0]);
			  BEGIN(INITIAL);
			  return ( TOKEN_REGEXP );
                        }
	YY_BREAK


case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 157 "expr-tokens.l"
{ nx_expr_parser_append_string(&(yylval->string), yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 158 "expr-tokens.l"
{ nx_expr_parser_append_string(&(yylval->string), yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 159 "expr-tokens.l"
{ 
			BEGIN(INITIAL); 
                        if ( yylval->string != NULL ) nx_string_unescape_c(yylval->string);
			return ( TOKEN_STRING );
		       }
	YY_BREAK

case 35:
YY_RULE_SETUP
#line 166 "expr-tokens.l"
return ( TOKEN_ASSIGNMENT );
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 167 "expr-tokens.l"
return ( TOKEN_NOT );
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 168 "expr-tokens.l"
return ( TOKEN_DEFINED );
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 169 "expr-tokens.l"
return ( TOKEN_AND );
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 170 "expr-tokens.l"
return ( TOKEN_OR );
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 171 "expr-tokens.l"
return ( TOKEN_XOR );
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 172 "expr-tokens.l"
return ( TOKEN_BINAND );
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 173 "expr-tokens.l"
return ( TOKEN_BINOR );
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 174 "expr-tokens.l"
return ( TOKEN_BINXOR );
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 175 "expr-tokens.l"
return ( TOKEN_IF );
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "expr-tokens.l"
return ( TOKEN_ELSE );
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 177 "expr-tokens.l"
return ( TOKEN_MUL );
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 178 "expr-tokens.l"
return ( TOKEN_DIV );
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 179 "expr-tokens.l"
return ( TOKEN_MOD );
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 180 "expr-tokens.l"
return ( TOKEN_PLUS );
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 181 "expr-tokens.l"
return ( TOKEN_MINUS );
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 182 "expr-tokens.l"
return ( TOKEN_EQUAL );
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 183 "expr-tokens.l"
return ( TOKEN_NOTEQUAL );
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 184 "expr-tokens.l"
return ( TOKEN_GE );
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 185 "expr-tokens.l"
return ( TOKEN_GREATER );
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 186 "expr-tokens.l"
return ( TOKEN_LE );
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 187 "expr-tokens.l"
return ( TOKEN_LESS );
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 188 "expr-tokens.l"
return ( TOKEN_LEFTBRACKET );
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 189 "expr-tokens.l"
return ( TOKEN_RIGHTBRACKET );
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 190 "expr-tokens.l"
return ( TOKEN_LEFTBRACE );
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 191 "expr-tokens.l"
return ( TOKEN_RIGHTBRACE );
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 192 "expr-tokens.l"
return ( TOKEN_SEMICOLON );
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 193 "expr-tokens.l"
return ( TOKEN_COMMA );
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 195 "expr-tokens.l"
{ yylval->string = nx_expr_parser_new_string(PARSER, yytext + 1); return ( TOKEN_FIELDNAME ); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 196 "expr-tokens.l"
{ yylval->string = nx_expr_parser_new_string(PARSER, yytext); return ( TOKEN_FUNCPROC ); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 197 "expr-tokens.l"
{ yylval->string = nx_expr_parser_new_string(PARSER, yytext); return ( TOKEN_FUNCPROC ); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 198 "expr-tokens.l"
{ yylval->string = nx_expr_parser_new_string(PARSER, yytext + 1); return ( TOKEN_CAPTURED ); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 201 "expr-tokens.l"
/* ignore blanks */
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 202 "expr-tokens.l"
/* ignore comment */
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 203 "expr-tokens.l"
PARSER->linepos = 0; (PARSER->linenum)++; /* reset column counter on new line */
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 204 "expr-tokens.l"
nx_expr_parser_error_fmt(PARSER, yyscanner, "invalid character: '%c'", yytext[0]);
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 206 "expr-tokens.l"
nx_expr_parser_error(PARSER, yyscanner, "syntax error");
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 208 "expr-tokens.l"
ECHO;
	YY_BREAK
#line 1453 "expr-tokens.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DOUBLEQUOTE):
case YY_STATE_EOF(SINGLEQUOTE):
case YY_STATE_EOF(REGEXPQUOTE):
case YY_STATE_EOF(REGEXPREPLACEQUOTE):
case YY_STATE_EOF(REGEXPREPLACEQUOTE2):
case YY_STATE_EOF(REGEXP):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * nx_expr_parser_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( nx_expr_parser_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of nx_expr_parser_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					nx_expr_parser_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			nx_expr_parser_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) nx_expr_parser_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 187 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 187 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 186);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					nx_expr_parser_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( nx_expr_parser_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void nx_expr_parser_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        nx_expr_parser_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            nx_expr_parser__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	nx_expr_parser__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	nx_expr_parser__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void nx_expr_parser__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		nx_expr_parser_pop_buffer_state();
	 *		nx_expr_parser_push_buffer_state(new_buffer);
     */
	nx_expr_parser_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	nx_expr_parser__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (nx_expr_parser_wrap()) processing, but the only time this flag
	 * is looked at is after nx_expr_parser_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void nx_expr_parser__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE nx_expr_parser__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) nx_expr_parser_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nx_expr_parser__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) nx_expr_parser_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in nx_expr_parser__create_buffer()" );

	b->yy_is_our_buffer = 1;

	nx_expr_parser__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with nx_expr_parser__create_buffer()
 * @param yyscanner The scanner object.
 */
    void nx_expr_parser__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		nx_expr_parser_free((void *) b->yy_ch_buf ,yyscanner );

	nx_expr_parser_free((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a nx_expr_parser_restart() or at EOF.
 */
    static void nx_expr_parser__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	nx_expr_parser__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then nx_expr_parser__init_buffer was _probably_
     * called from nx_expr_parser_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void nx_expr_parser__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		nx_expr_parser__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void nx_expr_parser_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	nx_expr_parser_ensure_buffer_stack(yyscanner);

	/* This block is copied from nx_expr_parser__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from nx_expr_parser__switch_to_buffer. */
	nx_expr_parser__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void nx_expr_parser_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	nx_expr_parser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		nx_expr_parser__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void nx_expr_parser_ensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)nx_expr_parser_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in nx_expr_parser_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)nx_expr_parser_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in nx_expr_parser_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE nx_expr_parser__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) nx_expr_parser_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nx_expr_parser__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	nx_expr_parser__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to nx_expr_parser_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       nx_expr_parser__scan_bytes() instead.
 */
YY_BUFFER_STATE nx_expr_parser__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return nx_expr_parser__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to nx_expr_parser_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE nx_expr_parser__scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) nx_expr_parser_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in nx_expr_parser__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = nx_expr_parser__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in nx_expr_parser__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE nx_expr_parser_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int nx_expr_parser_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int nx_expr_parser_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *nx_expr_parser_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *nx_expr_parser_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int nx_expr_parser_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *nx_expr_parser_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void nx_expr_parser_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void nx_expr_parser_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "nx_expr_parser_set_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void nx_expr_parser_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "nx_expr_parser_set_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see nx_expr_parser__switch_to_buffer
 */
void nx_expr_parser_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void nx_expr_parser_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int nx_expr_parser_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void nx_expr_parser_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * nx_expr_parser_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void nx_expr_parser_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* nx_expr_parser_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int nx_expr_parser_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) nx_expr_parser_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* nx_expr_parser_lex_init_extra has the same functionality as nx_expr_parser_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to nx_expr_parser_alloc in
 * the yyextra field.
 */

int nx_expr_parser_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    nx_expr_parser_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) nx_expr_parser_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    nx_expr_parser_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from nx_expr_parser_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * nx_expr_parser_lex_init()
     */
    return 0;
}

/* nx_expr_parser_lex_destroy is for both reentrant and non-reentrant scanners. */
int nx_expr_parser_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		nx_expr_parser__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		nx_expr_parser_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	nx_expr_parser_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        nx_expr_parser_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * nx_expr_parser_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    nx_expr_parser_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *nx_expr_parser_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *nx_expr_parser_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void nx_expr_parser_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see nx_expr_parser_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 208 "expr-tokens.l"




